#!/bin/bash
export DYLD_LIBRARY_PATH=/Applications/elastix_macosx64_v4.8/lib:$DYLD_LIBRARY_PATH

elastix -f mean_im.nii -m ./test-set/testing-images/1119.nii.gz -out ./test-set/registration-results/1119 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1019.nii.gz -out ./test-set/registration-results/1019 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1107.nii.gz -out ./test-set/registration-results/1107 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1023.nii.gz -out ./test-set/registration-results/1023 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1005.nii.gz -out ./test-set/registration-results/1005 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1025.nii.gz -out ./test-set/registration-results/1025 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1125.nii.gz -out ./test-set/registration-results/1125 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1113.nii.gz -out ./test-set/registration-results/1113 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1101.nii.gz -out ./test-set/registration-results/1101 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1039.nii.gz -out ./test-set/registration-results/1039 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1003.nii.gz -out ./test-set/registration-results/1003 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1122.nii.gz -out ./test-set/registration-results/1122 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1018.nii.gz -out ./test-set/registration-results/1018 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1004.nii.gz -out ./test-set/registration-results/1004 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1104.nii.gz -out ./test-set/registration-results/1104 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1116.nii.gz -out ./test-set/registration-results/1116 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1128.nii.gz -out ./test-set/registration-results/1128 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1024.nii.gz -out ./test-set/registration-results/1024 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1110.nii.gz -out ./test-set/registration-results/1110 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f mean_im.nii -m ./test-set/testing-images/1038.nii.gz -out ./test-set/registration-results/1038 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
