#!/bin/bash
export DYLD_LIBRARY_PATH=/Applications/elastix_macosx64_v4.8/lib:$DYLD_LIBRARY_PATH

# elastix -f ./test-set/testing-images/1113.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1113 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1110.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1110 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1039.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1039 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1005.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1005 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1025.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1025 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1122.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1122 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1119.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1119 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1128.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1128 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1023.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1023 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1003.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1003 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1101.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1101 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1024.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1024 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1019.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1019 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1038.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1038 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1018.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1018 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1004.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1004 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1116.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1116 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1104.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1104 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1125.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1125 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1107.nii.gz -m ./atlas/mean_im.nii -out ./test-set/registration-results/affine+bspline/1107 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt


# for the MNI atlas

# elastix -f ./test-set/testing-images/1113.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1113 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1110.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1110 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1039.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1039 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1005.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1005 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1025.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1025 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1122.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1122 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1119.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1119 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1128.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1128 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1023.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1023 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1003.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1003 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1101.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1101 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1024.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1024 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1019.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1019 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1038.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1038 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1018.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1018 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1004.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1004 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1116.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1116 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1104.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1104 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1125.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1125 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
# elastix -f ./test-set/testing-images/1107.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1107 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt

elastix -f ./test-set/testing-images/1039.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1039 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f ./test-set/testing-images/1122.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1122 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f ./test-set/testing-images/1023.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1023 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f ./test-set/testing-images/1019.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1019 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f ./test-set/testing-images/1038.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1038 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f ./test-set/testing-images/1018.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1018 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
elastix -f ./test-set/testing-images/1116.nii.gz -m ./MNITemplateAtlas/template.nii.gz -out ./test-set/registration-results/mni_templates/1116 -p ./training-set/par0000affine.txt -p ./training-set/par0000bspline.txt
