#!/bin/bash
export DYLD_LIBRARY_PATH=/Applications/elastix_macosx64_v4.8/lib:$DYLD_LIBRARY_PATH

transformix -in ./test-set/testing-labels/1128_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1128 -tp ./test-set/registration-results/affine+bspline/1128/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1019_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1019 -tp ./test-set/registration-results/affine+bspline/1019/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1125_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1125 -tp ./test-set/registration-results/affine+bspline/1125/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1110_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1110 -tp ./test-set/registration-results/affine+bspline/1110/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1038_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1038 -tp ./test-set/registration-results/affine+bspline/1038/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1104_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1104 -tp ./test-set/registration-results/affine+bspline/1104/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1116_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1116 -tp ./test-set/registration-results/affine+bspline/1116/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1018_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1018 -tp ./test-set/registration-results/affine+bspline/1018/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1039_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1039 -tp ./test-set/registration-results/affine+bspline/1039/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1122_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1122 -tp ./test-set/registration-results/affine+bspline/1122/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1023_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1023 -tp ./test-set/registration-results/affine+bspline/1023/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1004_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1004 -tp ./test-set/registration-results/affine+bspline/1004/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1025_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1025 -tp ./test-set/registration-results/affine+bspline/1025/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1119_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1119 -tp ./test-set/registration-results/affine+bspline/1119/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1003_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1003 -tp ./test-set/registration-results/affine+bspline/1003/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1107_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1107 -tp ./test-set/registration-results/affine+bspline/1107/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1113_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1113 -tp ./test-set/registration-results/affine+bspline/1113/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1005_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1005 -tp ./test-set/registration-results/affine+bspline/1005/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1024_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1024 -tp ./test-set/registration-results/affine+bspline/1024/TransformParameters.1.txt
transformix -in ./test-set/testing-labels/1101_3C.nii.gz -out ./test-set/registration-results/transformed-labels/1101 -tp ./test-set/registration-results/affine+bspline/1101/TransformParameters.1.txt
